apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: default
  labels:
    app: redis-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    nodePort: 6379
    targetPort: 6379
  selector:
    app: redis-pod
