apiVersion: v1
kind: Service
metadata:
  name: redis-svc-headless
  namespace: default
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    port: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-access
  namespace: default
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    nodePort: 6379
    targetPort: 6379
  selector:
    app: redis
