apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-conf
spec:
  capacity:
    storage: 64Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /export/nfs/mysql/conf
    server: omv.metazion.int
  ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /export/nfs/mysql/data
    server: omv.metazion.int
