apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
        image: mysql:8.0.13
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
          value: Root123456
        args:
          - '--default-authentication-plugin=mysql_native_password'
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-ps-conf
          mountPath: /etc/mysql
          - name: mysql-ps-data
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-ps-conf
        persistentVolumeClaim:
          claimName: mysql-pvc-conf
        - name: mysql-ps-data
        persistentVolumeClaim:
          claimName: mysql-pvc-data
