apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-conf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Mi
  ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
