apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: default
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - protocol: TCP
    port: 3306
    nodePort: 3306
    targetPort: 3306
  selector:
    app: mysql
