version: "3"
services:
  mysql:
    container_name: mysql_era
    image: mysql:8.0.20
    restart: always
    volumes:
      - $PWD/mysql/conf:/etc/mysql
      - $PWD/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - net_db
    environment:
      - MYSQL_ROOT_PASSWORD=Root123456
    command: ['--default-authentication-plugin=mysql_native_password']

  redis:
    container_name: redis_era
    image: redis:6.0.3
    restart: always
    volumes:
      - $PWD/redis/conf:/etc/redis
      - $PWD/redis/data:/data
    ports:
      - 6379:6379
    networks:
      - net_cache
    command: ['redis-server', '/etc/redis/redis.conf']

  zookeeper:
    container_name: zookeeper_era
    image: zookeeper:3.6.1
    restart: always
    volumes:
      - $PWD/zookeeper/conf/zoo.cfg:/conf/zoo.cfg
    ports:
      - 2181:2181
    networks:
      - net_ns

  etcd:
    container_name: etcd_era
    image: bitnami/etcd:3.4.9
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - net_ns
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  nacos:
    container_name: nacos_era
    image: nacos/nacos-server:1.2.1
    restart: always
    ports:
      - 8848:8848
    networks:
      - net_ns
    environment:
      - MODE=standalone

  rmqnamesrv:
    container_name: rmqnamesrv_era
    image: foxiswho/rocketmq:4.7.0
    restart: always
    volumes:
      - $PWD/rocketmq/namesrv/store:/opt/store
      - $PWD/rocketmq/namesrv/logs:/opt/logs
    ports:
      - 9876:9876
    networks:
      - net_mq
    environment:
      - 'JAVA_OPTS=-Duser.home=/opt'
      - 'JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn48m'
    command:
      - 'sh'
      - 'mqnamesrv'

  rmqbroker:
    container_name: rmqbroker_era
    image: foxiswho/rocketmq:4.7.0
    restart: always
    volumes:
      - $PWD/rocketmq/broker/conf/broker.conf:/etc/rocketmq/broker.conf
      - $PWD/rocketmq/broker/store:/opt/store
      - $PWD/rocketmq/broker/logs:/opt/logs
    ports:
      - 10909:10909
      - 10911:10911
    networks:
      - net_mq
    environment:
      - 'JAVA_OPTS=-Duser.home=/opt'
      - 'JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn48m'
    command:
      - 'sh'
      - 'mqbroker'
      - '-c'
      - '/etc/rocketmq/broker.conf'
    depends_on:
      - rmqnamesrv

  rmqconsole:
    container_name: rmqconsole_era
    image: styletang/rocketmq-console-ng:1.0.0
    restart: always
    ports:
      - 9888:8080
    networks:
      - net_mq
    environment:
      - 'JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv_era:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false'
    depends_on:
      - rmqnamesrv
      - rmqbroker

  tomcat_metazion_com:
    container_name: tomcat_metazion_com_era
    image: tomcat:9.0.35-jdk14-openjdk-oracle
    restart: always
    ports:
      - 8081:8080
    volumes:
      - $PWD/tomcat/metazion_com/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - $PWD/tomcat/metazion_com/webapps:/usr/local/tomcat/webapps
      - $PWD/tomcat/metazion_com/logs:/usr/local/tomcat/logs
    networks:
      - net_web

  nginx:
    container_name: nginx_era
    image: nginx:1.17.10
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf/cert:/etc/nginx/cert
      - $PWD/nginx/html:/var/share/nginx/html
      - $PWD/nginx/logs:/var/log/nginx
    networks:
      - net_web
    depends_on:
      - tomcat_metazion_com

networks:
  net_db:
    driver: bridge
  net_cache:
    driver: bridge
  net_ns:
    driver: bridge
  net_mq:
    driver: bridge
  net_web:
    driver: bridge
