version: '3'
services:
  tomcat_metazion_com:
    container_name: tomcat_metazion_com_era
    image: tomcat:9.0.35-jdk14-openjdk-oracle
    restart: always
    ports:
      - ${TOMCAT_METAZION_COM_HTTP_PORT}:8080
    volumes:
      - $PWD/tomcat/metazion_com/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - $PWD/tomcat/metazion_com/webapps:/usr/local/tomcat/webapps
      - $PWD/tomcat/metazion_com/logs:/usr/local/tomcat/logs
    networks:
      - net_web

  jarapp_com_metazion_official:
    container_name: jarapp_com_metazion_official_era
    image: registry.metazion.fun:5000/kaleofeng/jarapp:1.0-SNAPSHOT
    restart: always
    ports:
      - ${JARAPP_COM_METAZION_OFFICIAL_HTTP_PORT}:8080
    volumes:
      - $PWD/jarapp/com/metazion/official/bin:/data/bin
    networks:
      - net_web
    command:
      - 'java'
      - '-Xms64m'
      - '-Xmx64m'
      - '-jar'
      - './official.jar'

  nginx:
    container_name: nginx_era
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf/cert:/etc/nginx/cert
      - $PWD/nginx/html:/var/share/nginx/html
      - $PWD/nginx/logs:/var/log/nginx
    networks:
      - net_web
    depends_on:
      - tomcat_metazion_com

networks:
  net_web:
    driver: bridge
